export * from './user.routes'
export * from './difficulty.routes'
export * from './hero.routes'
export * from './character.routes'
export * from './article.routes'
export * from './read-article.routes'
